### ISSUE TITLE
IPFS Dataset downloading

### ISSUE THREAD

**Issue by SKioresku** [urbste/OpenImuCameraCalibrator#1]
I'm trying to download the dataset from the link, but it doesn't seem to work.

**Comment by SKioresku** [comment]
It was necessary to enter the following command ipfs get QmfRQmJcFu7TN4WFXwAbNMosvwo4heGKQtKbBSLpLPqFF7

**Comment by urbste** [comment]
I actually also changed the link to a google drive download link.

**Comment by urbste** [comment]
Let me know if the calibration works for you or if you face any issues.

**Comment by SKioresku** [comment]
> Let me know if the calibration works for you or if you face any issues.
I kept IMU and Images time in microseconds, but i have stange time_offset_gyro_to_cam after EstimateImuToCameraRotation
[imu_rotation_init.txt](https://github.com/urbste/OpenImuCameraCalibrator/files/6258922/imu_rotation_init.txt)

**Comment by SKioresku** [comment]
I am using this library with small modifications to calibrate my smartphone.

**Comment by SKioresku** [comment]
I changed some multipliers in these functions 
![Untitled](https://user-images.githubusercontent.com/18395805/113596513-18eb9680-9643-11eb-9c39-7385d52a5711.png)
![Untitled](https://user-images.githubusercontent.com/18395805/113594961-0d976b80-9641-11eb-832b-aaf2c00dd324.png)
![Untitled2](https://user-images.githubusercontent.com/18395805/113595086-328bde80-9641-11eb-8441-00677f9c794c.png)

**Comment by SKioresku** [comment]
> I actually also changed the link to a google drive download link.

Thanks)
