### ISSUE TITLE
Remove SSE2 on ARM64

### ISSUE THREAD

**Issue by SKioresku** [urbste/OpenImuCameraCalibrator#10]
I am trying to compile without SSE2 but I get errors.

**Comment by urbste** [comment]
Hi, first you would need to be a bit more specific: Where does the error occur? Is it in the OpenICC or another library?

Second I never tried to compile on ARM. Why would you want to do that?

**Comment by SKioresku** [comment]
Hi. I am building a library on nvidia jetson nano B1 to use it as a base for a robot

**Comment by SKioresku** [comment]
An error occurred in the vlfeat library

**Comment by SKioresku** [comment]
I want to transfer data from android to Nvidia Jetson to calibrate sensors

**Comment by urbste** [comment]
Ok. Could you not calibrate the sensors on a Laptop or a desktop PC?
 
I do not have the capacity to update any third party libraries sorry :/

**Comment by SKioresku** [comment]
I need to have the opportunity for the one who buys the robot to calibrate with it ))) I will try to disable SSE2 myself. It seems to be possible there, I just thought that TheiaSFM should have an option. Thanks))
