### ISSUE TITLE
GFLAGS error while compiling

### ISSUE THREAD

**Issue by sadsasuke** [urbste/OpenImuCameraCalibrator#13]
Hi i get these errors when compiling.

-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
CMake Error at cmake/FindGflags.cmake:121 (message):
  Failed to find gflags - Could not find gflags include directory, set
  GFLAGS_INCLUDE_DIR to directory containing gflags/gflags.h
Call Stack (most recent call first):
  cmake/FindGflags.cmake:464 (gflags_report_not_found)
  CMakeLists.txt:162 (find_package)

**Comment by urbste** [comment]
Hi, did you correctly install ceres-solver: http://ceres-solver.org/installation.html#linux? This should also install gflags.
