### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by sadsasuke** [urbste/OpenImuCameraCalibrator#14]
Hi, 
Is there a docker image for this tool? I am having issues with dependencies.

**Comment by urbste** [comment]
Hey, sorry no Dockerfile yet. I started one but it is not finished. However contributions are welcome :)

**Comment by ajsnyde** [comment]
I see that the Dockerfile just got committed yesterday! Thanks! Seriously simplifies installation and usage!
