### ISSUE TITLE
more precise Image timestamp from video after HERO8 Black

### ISSUE THREAD

**Issue by fushi219** [urbste/OpenImuCameraCalibrator#21]
Hi Steffen:
Sorry for my delayed action on GoPro max's calibration mr because of my busy work.

I think there is a better way to calculate each frame's timestamp than the method used below: 
https://github.com/urbste/OpenImuCameraCalibrator/blob/080cf97676e9ea3c9fe965e9cb4bd4628fea078c/python/extract_for_kalibr_bagcreator.py#L20

For cameras after Hero fusion, we can use the STMP in streams to calculate measure's precise timestamp. I have tested the imu's stamps calculated by STMP and gpmf-telemetry in your project, they are almost the same.

As you can see in this issue:  https://github.com/gopro/gpmf-parser/issues/160, for cameras after HERO8 Black (v2.5), we can use STMP in CORI streams to calculate more precise frame timestamp.(STMP in CORI does not start from 0.)

**Comment by urbste** [comment]
Hi fushi219. Thanks for that hint! I incorporated the precise timestamps for GoPro calibration.
