### ISSUE TITLE
ORB_SLAM3 fork bugs

### ISSUE THREAD

**Issue by cheng-chi** [urbste/OpenImuCameraCalibrator#31]
Hi Steffen, thank you so much for your work on GoPro SLAM! I'm a robotics PhD student trying to track a custom hand-held device with mounted GoPro. 
While trying to use your [https://github.com/urbste/ORB_SLAM3](https://github.com/urbste/ORB_SLAM3) repo, I found a lot of changes regarding to the DoubleSphere camera model was erased by a merge in master. Not sure if this is intentional.
Sorry about creating issue for another repo. Unforuntatley the issue tab on your ORB_SLAM3 repo is disabled.

**Comment by urbste** [comment]
Hi. Sorry for my late reply. I hope you were able to fix your issues with the fork? Closing the issue. Feel free to ask again if you have any question.s
