### ISSUE TITLE
Execution time

### ISSUE THREAD

**Issue by Styazoua** [urbste/OpenImuCameraCalibrator#36]
Can someone tell how long it takes do do the calibration?
I'm wating over 200 min and its still executing the calibration.

**Comment by Styazoua** [comment]
@urbste maybe you can give a feedback?

**Comment by urbste** [comment]
If you have issues with the runtime you might want to increase the
"voxel_grid_size" parameter to a larget value.
This will reduce the number of images that are going to be used for camera
calibration. In general you will not need >100 images.
Try a larger value until you have like 50-60 images. Then calibration
should be alot quicker.


Am Mi., 29. Nov. 2023 um 19:05 Uhr schrieb Styazoua <
***@***.***>:

**Comment by Styazoua** [comment]
Thanks for your fast respone.
I will test that.
