### ISSUE TITLE
How to config the quality value in the spline weight estimation?

### ISSUE THREAD

**Issue by zhoupengwei** [urbste/OpenImuCameraCalibrator#41]
@urbste Hi author, Thank you for share your project, How should I determine the sensor quality parameters of the get_sew_for_dataset.py. I found that different parameters produce different calibration results because they affect the weights in the final spline optimization process.

**Comment by urbste** [comment]
For this please check [this paper](https://openaccess.thecvf.com/content_cvpr_2018/papers/Ovren_Spline_Error_Weighting_CVPR_2018_paper.pdf). Also check Figure 6 and Equation 13.

In the end it is a hyperparameter and you have to find one that works good for your data. 

`To select a suitable knot spacing, ∆t, we thus first decide on a quality value, ˆ q ∈ (0, 1], that corresponds to the fraction of signal energy we want the approximation to retain.`
