### ISSUE TITLE
FindTheia.cmake is missing

### ISSUE THREAD

**Issue by Peungwon** [urbste/OpenImuCameraCalibrator#48]
FindTheia.cmake is missing and cmake .. does not work.

**Comment by urbste** [comment]
Could you please elaborate a bit more? I never had this issue. 
Did you follow the [guide](https://github.com/urbste/OpenImuCameraCalibrator?tab=readme-ov-file#installation-instructions).
Have you maybe forgotten to run `sudo make -j install` so that Theia is installed system wide?

**Comment by Peungwon** [comment]
I was eventually able to resolve this issue.
