### ISSUE TITLE
static_calib_result.json

### ISSUE THREAD

**Issue by gongping108** [urbste/OpenImuCameraCalibrator#7]
Can you provide static_calib_result.json or dataset2?

**Comment by gongping108** [comment]
I don't have the static_calib_result.json.
 I  comment "--imu_intrinsics="+args.path_to_imu_intrinsics, 
In  double reproj_error =
      imu_cam_calibrator.Optimize(20, false, false, false, true);  
The following error:
*** stack smashing detected ***: <unknown> terminated
the error occurrs in meanRSReprojection

**Comment by urbste** [comment]
Sorry for my late reply. I added a [description](https://github.com/urbste/OpenImuCameraCalibrator#example-intrinsic-imu-parameter-estimation)  on how to generate this file. I also updated the dataset you can find on Google Drive. It contains a sample file.

**Comment by gongping108** [comment]
Thank you very much!
