### ISSUE TITLE
Сalibration from a set of pictures

### ISSUE THREAD

**Issue by SKioresku** [urbste/OpenImuCameraCalibrator#9]
Is it possible to calibrate using a set of pictures like the kalibr does?

**Comment by urbste** [comment]
Yes it is possible but not documented.

The board_extractor can also extract from a set of PNG images. [look here](https://github.com/urbste/OpenImuCameraCalibrator/blob/master/src/core/board_extractor.cc#L176)

The filenames have to be the frametime in nanoseconds [here](https://github.com/urbste/OpenImuCameraCalibrator/blob/master/src/core/board_extractor.cc#L218)

There is also a python script that runs calibration on a Mynteye camera. [here](https://github.com/urbste/OpenImuCameraCalibrator/blob/master/python/run_mynteye_calibration.py#L97)
I will see if I can upload that as an example.
